# .github/workflows/snake.yml
name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: varunaditya27
          outputs: dist/snake.svg
          
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
